[
  {
    "pkg_repo": "Debian Main", 
    "pkg_full_name": "python3-zope.exceptions_4.0.7-1_all.deb", 
    "pkg": "python3-zope.exceptions", 
    "pkg_version": "4.0.7", 
    "release": ">=dev", 
    "os": "linux", 
    "distro": "debian"
  }, 
  {
    "pkg_repo": "Debian Main", 
    "pkg_full_name": "python3-zope.exceptions_4.0.7-1_all.deb", 
    "pkg": "python3-zope.exceptions", 
    "pkg_version": "4.0.7", 
    "release": ">=8.0", 
    "os": "linux", 
    "distro": "debian"
  }, 
  {
    "pkg_repo": "Debian Main", 
    "pkg_full_name": "python3-zope.exceptions_3.6.1-3_all.deb", 
    "pkg": "python3-zope.exceptions", 
    "pkg_version": "3.6.1", 
    "release": ">=7.0", 
    "os": "linux", 
    "distro": "debian"
  }, 
  {
    "pkg_repo": "Ubuntu Universe", 
    "pkg_full_name": "python3-zope.exceptions_4.0.7-1_all.deb", 
    "pkg": "python3-zope.exceptions", 
    "pkg_version": "4.0.7", 
    "release": ">=14.10", 
    "os": "linux", 
    "distro": "ubuntu"
  }, 
  {
    "pkg_repo": "Ubuntu Universe", 
    "pkg_full_name": "python3-zope.exceptions_4.0.6-1ubuntu2_all.deb", 
    "pkg": "python3-zope.exceptions", 
    "pkg_version": "4.0.6", 
    "release": ">=14.04", 
    "os": "linux", 
    "distro": "ubuntu"
  }
]